Class {
	#name : #FLWContractingFlowManager,
	#superclass : #WfWorkflowManager,
	#category : #'RunnableWorkflow-Kernel'
}

{ #category : #initialization }
FLWContractingFlowManager >> activationClass [
	^ FLWActivation
]

{ #category : #initialization }
FLWContractingFlowManager >> noteCompletionOf: anActivation in: aWorkList [



]

{ #category : #initialization }
FLWContractingFlowManager >> noteRunOf: anActivation in: aWorkList [

]

{ #category : #initialization }
FLWContractingFlowManager >> noteToken: aBoolean fromStep: aStep acceptedBy: anActivation [

]
